### ISSUE TITLE
Marketmaker changes required for GUI.

### ISSUE THREAD

**Issue by artemii235** [artemii235/etomic-swap#12]
1. Add ETH/ERC20 balance to `getCoin` RPC method.

**Comment by satindergrewal** [comment]
2. Add ETH/ERC20 balance to `portfolio` RPC method as well.
3. ETH/ERC20 withdraw needs to use `withdraw` method which returns raw transaction and that raw transaction needs to be processed by `sendrawtransaction` method.

**Comment by jl777** [comment]
it is probably much better to add ETH/ERC20 balance only to the places where it is actually getting a bitcoin type of balance. that way it is virtualizing the "balance" for the two types of coins

**Comment by artemii235** [comment]
@satindergrewal 
1. `getCoin` method now displays ETH/ERC20 balance. Changes are merged to jl777/dev branch so you can test it from there.
2. `portfolio` is periodically called by `trades_loop` which will cause many unnecessary balance requests. @jl777 should I use some cache? I'm also think to add a flag identifying either was `LP_portfolio` called by API or `trades_loop`.
3. withdraw->sendrawtransaction is not preferred for ETH/ERC20 - protocol is very different from bitcoin and uses special `nonce` parameter - there is a chance that received ETH raw transaction will conflict with already existing/pending. Is it ok to make a different behavior for ETH withdraw? It uses different API method anyway.

**Comment by artemii235** [comment]
Closing the issue as it's not actual anymore.
